### PR TITLE
Allow events to be cancelled in the 'before' callbacks

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by nathanvda** [comment]
Is it too much to ask to write some explanation how this should be used and documented? 

Also I think I see a typo? The second test only continues if default was prevented, is that intentional?

**Comment by wgordon17** [comment]
@nathanvda Sorry, I was in the middle of writing up the explanation in #203:

> It allows the before events to call e.preventDefault() to cancel any further processing.
My particular use case is for new records, if a user enters anything into a nested attribute, nothing stops them from accidentally deleting that row with all their "unsaved" data. And using confim:, I can't add the logic of checking if they've entered anything into the row. Otherwise it's a pain to have to confirm blank rows.
So, in my case, I'm checking if a user has selected anything in select dropdowns by adding up all the selected indexes, and if the sum is > 0, give them a confirm box. Calling e.preventDefault() if the confirm returns false is an easy solution.

**Comment by wgordon17** [comment]
@nathanvda I would be happy to update the README in this PR as well!

**Comment by nathanvda** [comment]
Yes, I really like the cleanliness and simplicity of this solution. If you would update the README I would greatly appreciate that :+1: :clap: :clap:

**Comment by wgordon17** [comment]
@nathanvda In testing, I found a typo with (jQuery.event -> jQuery.Event), which I fixed. I also updated the README, I hope that meets the standards you require for documentation.

**Comment by nathanvda** [comment]
Yes! Awesome work, thank you :+1:

**Comment by wgordon17** [comment]
Great! I'm glad to help out. Great gem!

**Comment by chamnap** [comment]
The solution above works with default `confirm` from the browser. However, it doesn't work with `sweetalert2` which uses promise. Do you guys have any clues dealing with this?

**Comment by nathanvda** [comment]
Please open a new ticket and provide some code-samples and links or explanations (what is `sweetalert2`? what are you trying, expecting and what are you getting).

**Comment by chamnap** [comment]
Thanks for reply @nathanvda. I'll open a new ticket soon.

**Pull request merged**
