### PR TITLE
Feature/i18n conventions issue 36

### PR DESCRIPTION
**Pull request by ViliusLuneckas**
Hello,

I'm using this awesome `gem` together with `simple_form`. As you know `simple_form` has nice `I18n` support and I wish cocoon would have it too (related to https://github.com/nathanvda/cocoon/issues/36).

I hope you find this interesting and adding value.

Vilius

### CODE REVIEW

**Comment by nathanvda** [comment]
Nice work! Can you add some documentation as well?

**Comment by ViliusLuneckas** [comment]
@nathanvda, I've never wrote documentation before, does it make sense to you? e0e22409d2c6d6980ded5f2ba09faa15e97fa6af

**Comment by nathanvda** [comment]
Awesome work, thanks :+1: :+1:

**Comment by nathanvda** [comment]
I want to add another minor fix,I will release this version this weekend. Thank you very much!!!

**Pull request merged**
