### PR TITLE
Fix for issue #402 - Change text links to buttons

### PR DESCRIPTION
**Pull request by p12y**
Changed the text links in link_to_remove_association and link_to_add_association to buttons. I also updated the specs to suit this.

### CODE REVIEW

**Comment by nathanvda** [comment]
Thank you for your effort in this PR. I preferred if you had reached out first, because you now just changed all links to buttons, that is not what I had in mind (not clear from the explanation in the issue, I understand). 

I am not going to merge this, because this is not backward compatible at all. 

You do not see the problem that all methods are called `link_to_...` and then suddenly generate buttons? 

I want the current functionality to remain the same, and if the user wants a button, they should call an alternative method `button_to_add_association` or `button_to_remove_association`. I have already started implementing this, trying to duplicate as least code as possible.

If you are willing to work on it further, I would appreciate it. But I understand if it now works perfectly for you. Otherwise I will try to finish it later this week.

**Comment by nathanvda** [comment]
(and yes I need to fix the travis ci build, e.g. rubinius is always giving me troubles, and I try to run the build against rails 3 and rails4, I still have to rails 5, and a range of ruby versions, some of which are outdated)

**Comment by PeteTyldesley** [comment]
Thanks for the feedback @nathanvda. I understand you completely now. That would make a lot more sense that way for sure. If you don't mind I'll have another stab at it tomorrow and I'll make sure to avoid any unnecessary repetition.

**Comment by PeteTyldesley** [comment]
@nathanvda Do you think you can use this? I created separate methods for link_to and button_to. I updated the specs which are all passing on my machine.

**Pull request closed without merging**
