### PR TITLE
Fix tests, CI and move to RSpec 3.

### PR DESCRIPTION
**Pull request by simi**

### CODE REVIEW

**Comment by simi** [comment]
@nathanvda hello!

Is there any chance to enable Travis CI again?

**Comment by nathanvda** [comment]
Thank you for your effort. I never disabled travis CI. It just does not build correctly. 

Did you check that this is backwards compatible? E.g. it works with the gemfile in the `gemfiles` folder? Cocoon is tested against rails 3 and rails 4.

I hope to have a good look later tonight, as I am currently trying to add a new feature too, so I will try to integrate this as well.

**Comment by simi** [comment]
Hmm, that's weird @nathanvda. Why PR's are not builded also?

**Comment by simi** [comment]
I changed 3.2.13 Gemfile to use ~> 3.0 RSpec. It passes without error or warning also.

**Comment by nathanvda** [comment]
Awesome, thanks! Let me check why PR's are not built.

**Comment by simi** [comment]
Rubinius build is still broken. But I have no idea why (bundler fails).

**Comment by nathanvda** [comment]
Yes I just saw it too. Also got me puzzled. I like to include rbx for completeness. Anyway: great work and thanks for your help! Maybe I need to update the rbx platform/version again.

I saw on the website the mechanism had changed, so I updated my information and I am hoping now forks/pull requests will also be built. I just had a hook before, on each push to master, but now I enabled the complete repo for travis.

**Pull request merged**
