### PR TITLE
Hide destroyed fields on document ready

### PR DESCRIPTION
**Pull request by Tensho**

### CODE REVIEW

**Comment by nathanvda** [comment]
Is there an actual reason for this change? All the code is already executed when the document is ready. I am using the shorthand form: http://learn.jquery.com/using-jquery-core/document-ready/

**Comment by nathanvda** [comment]
Ah, wait: I might be confused :confused: :smile:

**Comment by Tensho** [comment]
I'm not pro in js ^_^ but it seams to me you just used [immediately-invoked function expression](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) to produce lexical scope. I've traced `cocoon.js` till the mentioned piece of code and found unloaded DOM.

**Comment by Tensho** [comment]
@nathanvda, do you have other concerns about this PR?

**Comment by nathanvda** [comment]
At the moment I am in the process of refactoring the js, also your code is not turbolinks compatible. So I am waiting. But at the moment not finding much time to actually finish my refactoring. Sorry.

**Comment by nathanvda** [comment]
This is now fixed in turbolinks compliant way.

**Comment by Tensho** [comment]
👍

**Pull request closed without merging**
