### PR TITLE
Added a limit condition that interrupt insertion

### PR DESCRIPTION
**Pull request by rubensmabueno**
As mentioned in https://github.com/nathanvda/cocoon/issues/194, I made a contribution that consider a limit condition in parameter as:

``` ruby
link_to_add_association 'Add Association', f, :associations, limit: 3
```

and interrupt the insertion the nested associations in that node and also trigger the event `cocoon:limit-reached`.

### CODE REVIEW

**Comment by raulgarciadev** [comment]
Hi, can I use this to limit insertions? how?

**Comment by bekicot** [comment]
+1

**Comment by afilipko** [comment]
+1

**Comment by TangMonk** [comment]
not merged?

**Comment by anark** [comment]
+1

**Comment by EdwinRozario** [comment]
+1 Hope it make the add button disappear with a 'limit reached' message on it.

**Comment by olesyakorovina** [comment]
+1

**Comment by jjahaziel** [comment]
I try to do this but nothing.

**Comment by listerblog** [comment]
+1

**Comment by nathanvda** [comment]
This is old, but I am cleaning up. Sorry I never replied to this before. 

Not merged because it is easy to implement using callbacks, and there are imho different approaches based on your UX. In my opinion implemented like in this PR encourages bad UX (show a link and only after click we start counting where imho we know _beforehand_ clicking the link would not be allowed)

Example implementation: https://github.com/nathanvda/cocoon/wiki/How-to-limit-the-number-of-nested-fields

**Pull request closed without merging**
