### PR TITLE
Add extra properties to insertion events

### PR DESCRIPTION
**Pull request by ayaman**
Added extra properties to give access to the association type and link to `cocoon:before-insert` and `cocoon:after-insert`. This resolves the issue mentioned in #465.

### CODE REVIEW

**Comment by Mirv** [comment]
Nice

**Comment by nathanvda** [comment]
Mmmm I do not quite understand the purpose of this PR? When handling the event `this` is set correctly to the link (so passing it down has no use?) and I would assume the association would also be clear (and once you have `this` supposing you have to handle different associations in one callback, you can easily read the `data-association` attribute?). 

Please explain (and the linked ticket does not give enough details imho --attributes is pretty general only to then hand very specific attributes down does not make sense to me?)

**Comment by ayaman** [comment]
I agree that there's no need for the "assoc" property since it can be accessed through the link's data attributes, I somehow missed that while going through the code.

As for passing the link, I couldn't figure out a way to get it through the event as you described since `this` points to the element on which the event is monitored or from which it started, and that always seems to be the container into which content is inserted or one of its ancestors, but the link doesn't necessarily need to be in one of those.

**Comment by K1N5L4Y3R** [comment]
If there is currently no other way to reference the original click event on the 'Add association' link, I am in favor of having this merged to the repo. My use case is that I'm manually triggering click events on the 'Add association' link (since AFAIK there's no API to add an association). I need to do some work by listening to the `cocoon:before-insert`event, but I need to know _what_ triggered it (since I'm doing multiple inserts, and passing custom event data on each `click` event I trigger and I need to have access to this data).

**Comment by ayaman** [comment]
Closing this PR since #552 solves the original issue. Thank you @K1N5L4Y3R!

**Pull request closed without merging**
