### PR TITLE
Turbolinks README

### PR DESCRIPTION
**Pull request by itsNikolay**

### CODE REVIEW

**Comment by simi** [comment]
:+1:

**Comment by nathanvda** [comment]
Did you actually test this? Because according to the documentation this will fail: upon multiple page-reloads it will bind several click-handlers to the same event. The cocoon js is ok with turbolinks, there is only one small part that does not work: the hiding of the already deleted nested items, re-rendered after validation error. I am currently fixing this in the js.

**Comment by itsNikolay** [comment]
Seems as working, but I will recheck it with described cases one more.

**Comment by nathanvda** [comment]
Cocoon is now turbolinks compliant.

**Pull request closed without merging**
